// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package apicontract

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AuthorizationPendingResponseError.
const (
	AuthorizationPending AuthorizationPendingResponseError = "authorization_pending"
)

// Defines values for BillingRequiredResponseErrorCode.
const (
	BillingRequired BillingRequiredResponseErrorCode = "billing_required"
)

// Defines values for BillingRequiredResponseErrorState.
const (
	ActivePaid     BillingRequiredResponseErrorState = "active_paid"
	GrantActive    BillingRequiredResponseErrorState = "grant_active"
	Inactive       BillingRequiredResponseErrorState = "inactive"
	ManualOverride BillingRequiredResponseErrorState = "manual_override"
	NoSubscription BillingRequiredResponseErrorState = "no_subscription"
	PastDue        BillingRequiredResponseErrorState = "past_due"
	Trial          BillingRequiredResponseErrorState = "trial"
)

// Defines values for ChainStatus.
const (
	Broken     ChainStatus = "broken"
	Unverified ChainStatus = "unverified"
	Valid      ChainStatus = "valid"
)

// Defines values for DeviceCodeRequestClientId.
const (
	CordonCli DeviceCodeRequestClientId = "cordon-cli"
)

// Defines values for EventsBehindResponseError.
const (
	EventsBehind EventsBehindResponseError = "events_behind"
)

// Defines values for Role.
const (
	Admin  Role = "admin"
	Member Role = "member"
)

// Defines values for TokenRequestGrantType.
const (
	UrnIetfParamsOauthGrantTypeDeviceCode TokenRequestGrantType = "urn:ietf:params:oauth:grant-type:device_code"
)

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "bearer"
)

// AuditLogEntry defines model for AuditLogEntry.
type AuditLogEntry struct {
	Agent      *string   `json:"agent,omitempty"`
	Detail     *string   `json:"detail,omitempty"`
	EventType  string    `json:"event_type"`
	FilePath   *string   `json:"file_path,omitempty"`
	FileRuleId *string   `json:"file_rule_id,omitempty"`
	Hash       *string   `json:"hash,omitempty"`
	Id         int64     `json:"id"`
	ParentHash *string   `json:"parent_hash,omitempty"`
	PassId     *string   `json:"pass_id,omitempty"`
	Timestamp  time.Time `json:"timestamp"`
	ToolName   *string   `json:"tool_name,omitempty"`
	User       *string   `json:"user,omitempty"`
}

// AuthorizationPendingResponse defines model for AuthorizationPendingResponse.
type AuthorizationPendingResponse struct {
	Error AuthorizationPendingResponseError `json:"error"`
}

// AuthorizationPendingResponseError defines model for AuthorizationPendingResponse.Error.
type AuthorizationPendingResponseError string

// BillingRequiredResponse defines model for BillingRequiredResponse.
type BillingRequiredResponse struct {
	Error struct {
		Code    BillingRequiredResponseErrorCode  `json:"code"`
		Message string                            `json:"message"`
		State   BillingRequiredResponseErrorState `json:"state"`
	} `json:"error"`
}

// BillingRequiredResponseErrorCode defines model for BillingRequiredResponse.Error.Code.
type BillingRequiredResponseErrorCode string

// BillingRequiredResponseErrorState defines model for BillingRequiredResponse.Error.State.
type BillingRequiredResponseErrorState string

// ChainStatus defines model for ChainStatus.
type ChainStatus string

// DataIngestAccepted defines model for DataIngestAccepted.
type DataIngestAccepted struct {
	AuditLog int `json:"audit_log"`
	HookLog  int `json:"hook_log"`
	Passes   int `json:"passes"`
	Sessions int `json:"sessions"`
}

// DataIngestChainStatus defines model for DataIngestChainStatus.
type DataIngestChainStatus struct {
	AuditLog *ChainStatus `json:"audit_log,omitempty"`
	HookLog  *ChainStatus `json:"hook_log,omitempty"`
}

// DataIngestRequest Current server behavior accepts sparse payloads; all top-level properties are optional.
// Older clients may omit client_id.
type DataIngestRequest struct {
	AuditLog *[]AuditLogEntry `json:"audit_log,omitempty"`

	// ClientId UUID preferred. Non-UUID values are accepted.
	ClientId   *string           `json:"client_id,omitempty"`
	HookLog    *[]HookLogEntry   `json:"hook_log,omitempty"`
	Passes     *[]Pass           `json:"passes,omitempty"`
	Sessions   *[]Session        `json:"sessions,omitempty"`
	Watermarks *IngestWatermarks `json:"watermarks,omitempty"`
}

// DataIngestResponse defines model for DataIngestResponse.
type DataIngestResponse struct {
	Accepted               DataIngestAccepted    `json:"accepted"`
	ChainStatus            DataIngestChainStatus `json:"chain_status"`
	ClientId               string                `json:"client_id"`
	NotificationsTriggered int                   `json:"notifications_triggered"`
}

// DeviceCodeRequest defines model for DeviceCodeRequest.
type DeviceCodeRequest struct {
	ClientId DeviceCodeRequestClientId `json:"client_id"`
}

// DeviceCodeRequestClientId defines model for DeviceCodeRequest.ClientId.
type DeviceCodeRequestClientId string

// DeviceCodeResponse defines model for DeviceCodeResponse.
type DeviceCodeResponse struct {
	DeviceCode      string `json:"device_code"`
	ExpiresIn       int    `json:"expires_in"`
	Interval        int    `json:"interval"`
	UserCode        string `json:"user_code"`
	VerificationUri string `json:"verification_uri"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// EventsBehindResponse defines model for EventsBehindResponse.
type EventsBehindResponse struct {
	Error   EventsBehindResponseError `json:"error"`
	Message *string                   `json:"message,omitempty"`
}

// EventsBehindResponseError defines model for EventsBehindResponse.Error.
type EventsBehindResponseError string

// HookLogEntry defines model for HookLogEntry.
type HookLogEntry struct {
	Agent                *string `json:"agent,omitempty"`
	Ambiguity            *string `json:"ambiguity,omitempty"`
	CommandOpsJson       *string `json:"command_ops_json,omitempty"`
	CommandParseError    *string `json:"command_parse_error,omitempty"`
	CommandParsedOk      *bool   `json:"command_parsed_ok,omitempty"`
	CommandParser        *string `json:"command_parser,omitempty"`
	CommandParserVersion *string `json:"command_parser_version,omitempty"`
	CommandRaw           *string `json:"command_raw,omitempty"`
	Decision             string  `json:"decision"`
	DeniedOpIndex        *int    `json:"denied_op_index,omitempty"`
	DeniedOpReason       *string `json:"denied_op_reason,omitempty"`
	FilePath             string  `json:"file_path"`
	Hash                 *string `json:"hash,omitempty"`
	Id                   int64   `json:"id"`
	MatchedRulePattern   *string `json:"matched_rule_pattern,omitempty"`
	MatchedRuleType      *string `json:"matched_rule_type,omitempty"`
	Notify               *bool   `json:"notify,omitempty"`
	OsUser               *string `json:"os_user,omitempty"`
	ParentHash           *string `json:"parent_hash,omitempty"`
	PassId               *string `json:"pass_id,omitempty"`
	SecretRuleIds        *string `json:"secret_rule_ids,omitempty"`
	SecretsDetected      *int    `json:"secrets_detected,omitempty"`
	SessionId            *string `json:"session_id,omitempty"`
	ToolInput            *string `json:"tool_input,omitempty"`
	ToolName             string  `json:"tool_name"`
	TranscriptPath       *string `json:"transcript_path,omitempty"`

	// Ts Unix timestamp in microseconds.
	Ts int64 `json:"ts"`
}

// IngestWatermarks defines model for IngestWatermarks.
type IngestWatermarks struct {
	AuditLog           *int64     `json:"audit_log,omitempty"`
	HookLog            *int64     `json:"hook_log,omitempty"`
	PassesLastSyncedAt *time.Time `json:"passes_last_synced_at,omitempty"`
	Sessions           *int64     `json:"sessions,omitempty"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Perimeters []PerimeterSummary `json:"perimeters"`
	User       UserProfile        `json:"user"`
}

// Pass defines model for Pass.
type Pass struct {
	ExpiresAt  *time.Time `json:"expires_at,omitempty"`
	FileRuleId *string    `json:"file_rule_id,omitempty"`
	Id         string     `json:"id"`
	IssuedAt   time.Time  `json:"issued_at"`
	IssuedBy   string     `json:"issued_by"`
	IssuedTo   string     `json:"issued_to"`
	Pattern    string     `json:"pattern"`
	RevokedAt  *time.Time `json:"revoked_at,omitempty"`
	RevokedBy  *string    `json:"revoked_by,omitempty"`
	Status     string     `json:"status"`
}

// PerimeterLookupResponse defines model for PerimeterLookupResponse.
type PerimeterLookupResponse struct {
	Name        string `json:"name"`
	PerimeterId string `json:"perimeter_id"`
	Role        Role   `json:"role"`
}

// PerimeterSummary defines model for PerimeterSummary.
type PerimeterSummary struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Role Role   `json:"role"`
}

// PolicyEvent defines model for PolicyEvent.
type PolicyEvent struct {
	Actor      string  `json:"actor"`
	EventId    string  `json:"event_id"`
	EventType  string  `json:"event_type"`
	Hash       *string `json:"hash,omitempty"`
	ParentHash *string `json:"parent_hash,omitempty"`

	// Payload JSON string payload.
	Payload   string `json:"payload"`
	ServerSeq *int64 `json:"server_seq,omitempty"`

	// Timestamp ISO 8601 string in current implementations.
	Timestamp string `json:"timestamp"`
}

// PolicyPullResponse defines model for PolicyPullResponse.
type PolicyPullResponse struct {
	Events  []PolicyEvent `json:"events"`
	HasMore bool          `json:"has_more"`
}

// PolicyPushRequest defines model for PolicyPushRequest.
type PolicyPushRequest struct {
	Events             []PolicyEvent `json:"events"`
	LastKnownServerSeq int64         `json:"last_known_server_seq"`
}

// PolicyPushResponse defines model for PolicyPushResponse.
type PolicyPushResponse struct {
	Accepted             int              `json:"accepted"`
	ServerSeqAssignments map[string]int64 `json:"server_seq_assignments"`
}

// Role defines model for Role.
type Role string

// Session defines model for Session.
type Session struct {
	Agent           string `json:"agent"`
	CacheReadTokens int64  `json:"cache_read_tokens"`
	Description     string `json:"description"`
	FirstSeenAt     int64  `json:"first_seen_at"`
	InputTokens     int64  `json:"input_tokens"`
	LastSeenAt      int64  `json:"last_seen_at"`
	OutputTokens    int64  `json:"output_tokens"`
	SessionId       string `json:"session_id"`
	TranscriptPath  string `json:"transcript_path"`
	UpdatedAt       int64  `json:"updated_at"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	DeviceCode string                `json:"device_code"`
	GrantType  TokenRequestGrantType `json:"grant_type"`
}

// TokenRequestGrantType defines model for TokenRequest.GrantType.
type TokenRequestGrantType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string                 `json:"access_token"`
	ExpiresIn   int                    `json:"expires_in"`
	TokenType   TokenResponseTokenType `json:"token_type"`
	User        UserProfile            `json:"user"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UserProfile defines model for UserProfile.
type UserProfile struct {
	AvatarUrl   string `json:"avatar_url"`
	DisplayName string `json:"display_name"`
	Id          string `json:"id"`
	Username    string `json:"username"`
}

// PerimeterId defines model for PerimeterId.
type PerimeterId = string

// PerimetersLookupParams defines parameters for PerimetersLookup.
type PerimetersLookupParams struct {
	PerimeterId string `form:"perimeter_id" json:"perimeter_id"`
}

// PolicyEventsPullParams defines parameters for PolicyEventsPull.
type PolicyEventsPullParams struct {
	AfterServerSeq int64 `form:"after_server_seq" json:"after_server_seq"`

	// Limit Clamped server-side to 1..1000
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AuthDeviceJSONRequestBody defines body for AuthDevice for application/json ContentType.
type AuthDeviceJSONRequestBody = DeviceCodeRequest

// AuthTokenJSONRequestBody defines body for AuthToken for application/json ContentType.
type AuthTokenJSONRequestBody = TokenRequest

// DataIngestJSONRequestBody defines body for DataIngest for application/json ContentType.
type DataIngestJSONRequestBody = DataIngestRequest

// PolicyEventsPushJSONRequestBody defines body for PolicyEventsPush for application/json ContentType.
type PolicyEventsPushJSONRequestBody = PolicyPushRequest
